name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        continue-on-error: true

  build:
    needs: security-scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./VulnerableApi.csproj

      - name: Build
        run: dotnet build ./VulnerableApi.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./VulnerableApi.csproj -c Release -o ./publish

      - name: Build Docker image
        run: docker build -t vulnerable-api:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: vulnerable-api:latest
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'